name: Java CI/CD with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        mvn -B install -DskipTests
        mvn -B package --file pom.xml
      
    - name: Prepare artifacts
      run: |
        mkdir -p app/modules
        cp core/target/ROOT.war app/
        cp modules/*/target/*.jar app/modules/
        mkdir -p lib
        cp core/target/ROOT-lib.jar lib/sema-lib.jar
        [ -f "app/ROOT.war" ] || exit 1
        [ "$(ls -A app/modules)" ] || exit 1
        
    - name: Upload built app artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: app/
        retention-days: 1

  deploy:
    needs: check-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Only deploy on master branch
    
    steps:
    - name: Upload built lib artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lib-package
        path: lib/
        retention-days: 1
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-package
        path: app/
        
    - name: Verify downloaded files
      run: |
        [ -f "app/ROOT.war" ] || exit 1
        [ "$(ls -A app/modules)" ] || exit 1
        
    - name: Create deployment package
      run: tar -czvf app.tar.gz app/
    - name: Deploy package
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "app.tar.gz"
        target: "/${{ secrets.SERVER_USERNAME }}/sema/"
        overwrite: true
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /${{ secrets.SERVER_USERNAME }}/sema
          ./deploy.sh
