name: Build and Deploy to maven repository

on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Set up JDK 21 for Github package
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots install
    - name: Deploy to GitHub
      run: mvn --batch-mode -DskipTests -DuseGitHubPackages=true deploy -pl core -am
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    - name: Create bundle.zip from assets
      run: |
        mkdir bundle
        cp core/target/core* bundle/
        zip -j bundle.zip bundle/*

    - name: Encode Central credentials
      run: |
        echo "AUTH_HEADER=$(echo -n '${{ secrets.OSSRH_USERNAME }}:${{ secrets.OSSRH_TOKEN }}' | base64)" >> $GITHUB_ENV
    - name: Upload bundle.zip with curl
      run: |
        curl --request POST \
          --verbose \
          --header "Authorization: Bearer $AUTH_HEADER" \
          --form bundle=@bundle.zip \
          https://central.sonatype.com/api/v1/publisher/upload
