name: Build and Deploy to maven repository

on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots install
    - name: Deploy to GitHub
      run: mvn --batch-mode -DskipTests -DuseGitHubPackages=true deploy
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
